// <auto-generated />
using System;
using ConcertsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConcertsAPI.Migrations
{
    [DbContext(typeof(ConcertsDbContext))]
    [Migration("20220524183939_SeedAgainWithoutPoster")]
    partial class SeedAgainWithoutPoster
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConcertsAPI.Data.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistName = "Nirvana",
                            ContactEmail = "dannyg@nirvana.com",
                            ContactPhoneNumber = "4647478",
                            ManagerLastName = "Goldberg",
                            ManagerName = "Danny",
                            Nationality = "American"
                        },
                        new
                        {
                            Id = 2,
                            ArtistName = "Kat Frankie",
                            ContactEmail = "carolj@manager.com",
                            ContactPhoneNumber = "31638268",
                            ManagerLastName = "Jordan",
                            ManagerName = "Carol",
                            Nationality = "Australian"
                        },
                        new
                        {
                            Id = 3,
                            ArtistName = "Tarkan",
                            ContactEmail = "benjamink@tarkan.com",
                            ContactPhoneNumber = "5646467",
                            ManagerLastName = "Kaya",
                            ManagerName = "Benjamin",
                            Nationality = "Turkish"
                        });
                });

            modelBuilder.Entity("ConcertsAPI.Data.Concert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventRules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<double>("TicketPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("PlaceId");

                    b.ToTable("Concerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Date = new DateTime(2022, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventRules = "-There is 18 age limit.- Participants / viewers must follow the rules received under COVID-19.",
                            PlaceId = 1,
                            TicketPrice = 240.0
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 1,
                            Date = new DateTime(2022, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventRules = "-There is 18 age limit.- Participants / viewers must follow the rules received under COVID-19.",
                            PlaceId = 2,
                            TicketPrice = 100.0
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 2,
                            Date = new DateTime(2022, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventRules = "-There is 18 age limit.- Participants / viewers must follow the rules received under COVID-19.",
                            PlaceId = 1,
                            TicketPrice = 150.0
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 2,
                            Date = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventRules = "-There is 18 age limit.- Participants / viewers must follow the rules received under COVID-19.",
                            PlaceId = 3,
                            TicketPrice = 1000.0
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 3,
                            Date = new DateTime(2022, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventRules = "-There is 18 age limit.- Participants / viewers must follow the rules received under COVID-19.",
                            PlaceId = 1,
                            TicketPrice = 300.0
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 3,
                            Date = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventRules = "-There is 18 age limit.- Participants / viewers must follow the rules received under COVID-19.",
                            PlaceId = 2,
                            TicketPrice = 530.0
                        });
                });

            modelBuilder.Entity("ConcertsAPI.Data.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdressDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdressDetails = "Visnezade, Dolmabahce No:1, 34357",
                            City = "Istanbul",
                            ContactEmail = "management@vodafonearena.com",
                            ContactPhoneNumber = "12412422",
                            Country = "Turkey",
                            Name = "Vodafone Arena"
                        },
                        new
                        {
                            Id = 2,
                            AdressDetails = "Peninsula Square, London SE10 0DX",
                            City = "London",
                            ContactEmail = "management@o2arena.com",
                            ContactPhoneNumber = "12892422",
                            Country = "UK",
                            Name = "The O2 Arena"
                        },
                        new
                        {
                            Id = 3,
                            AdressDetails = "2-3 Kitanomarukoen, Chiyoda City, Tokyo 102-8321",
                            City = "Tokyo",
                            ContactEmail = "management@nipponbudokann.com",
                            ContactPhoneNumber = "398923221",
                            Country = "Japan",
                            Name = "Nippon Budokann"
                        });
                });

            modelBuilder.Entity("ConcertsAPI.Data.Concert", b =>
                {
                    b.HasOne("ConcertsAPI.Data.Artist", "Artist")
                        .WithMany("Concerts")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConcertsAPI.Data.Place", "Place")
                        .WithMany("Concerts")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("ConcertsAPI.Data.Artist", b =>
                {
                    b.Navigation("Concerts");
                });

            modelBuilder.Entity("ConcertsAPI.Data.Place", b =>
                {
                    b.Navigation("Concerts");
                });
#pragma warning restore 612, 618
        }
    }
}
